import 'package:sugar_wise/features/doctor/doctor_view_patient/model/doctor_model.dart';

final List<DoctorModle> globalDoctorsList = [
  DoctorModle(
    id: 1, // أو '1' حسب نوع البيانات عندك
    name: ' Basil Ashraf',
    specialty: 'Endocrine Glands',
    image: 'assets/images/doctor/doc1.jpg',
    rating: 4.8,
    expYears: 10,
    age: 25,
    workplace: 'Cairo Medical Center',
    location: 'Cairo Medical Center, Fayoum',
    biograph: '',
  ),
  DoctorModle(
    id: 2,
    name: 'Yosef Khattab',
    specialty: 'Cardiologist',
    image: 'assets/images/doctor/doc2.jpg',
    rating: 4.5,
    expYears: 10,
    age: 25,
    workplace: '',
    location: 'Cairo Medical Center, cairo',
  ),
  DoctorModle(
    id: 3,
    name: 'Rawan Yusry',
    specialty: 'Heart Surgeon',
    image: 'assets/images/doctor/doc3.jpg',
    rating: 4.8,
    expYears: 10,
    age: 25,
    workplace: '',
    location: 'Cairo Medical Center, cairo',
  ),
  DoctorModle(
    id: 4,
    name: 'Shahed',
    specialty: 'Heart Surgeon',
    image: 'assets/images/doctor/doc1.jpg',
    rating: 4.8,
    expYears: 10,
    age: 25,
    workplace: '',
    location: 'Cairo Medical Center, cairo',
  ),
  DoctorModle(
    id: 5,
    name: 'May',
    specialty: 'Cardiologist',
    image: 'assets/images/doctor/doc2.jpg',
    rating: 4.5,
    expYears: 10,
    age: 25,
    workplace: '',
    location: 'Cairo Medical Center, cairo',
  ),
  DoctorModle(
    id: 6,
    name: 'Alaa ',
    specialty: 'Cardiologist',
    image: 'assets/images/doctor/doc2.jpg',
    rating: 4.5,
    expYears: 10,
    age: 25,
    workplace: '',
    location: 'Cairo Medical Center, cairo',
  ),
  DoctorModle(
    id: 7,
    name: 'Fatma',
    specialty: 'Cardiologist',
    image: 'assets/images/doctor/doc2.jpg',
    rating: 4.5,
    expYears: 10,
    age: 25,
    workplace: '',
    location: 'Cairo Medical Center, cairo',
  ),
  DoctorModle(
    id: 8,
    name: 'Mariam',
    specialty: 'Cardiologist',
    image: 'assets/images/doctor/doc2.jpg',
    rating: 4.5,
    expYears: 10,
    age: 25,
    workplace: '',
    location: 'Cairo Medical Center, cairo',
  ),
  DoctorModle(
    id: 9,
    name: 'mohamed ',
    specialty: 'Pharmacy',
    image: 'assets/images/doctor/doc5.jpeg',
    rating: 4.5,
    expYears: 1,
    age: 19,
    workplace: '',
    location: 'Cairo Medical Center, cairo',
  ),
];
